version: '3'

services:
 joplin-db:
  image: postgres:13
  restart: always
  volumes:
   -./joplin_data:/var/lib/postgresql/data
  environment:
   POSTGRES_USER: joplin
   POSTGRES_PASSWORD: Btctgrp6.eve
   POSTGRES_DB: joplin
  healthcheck: 
   test: ["CMD-SHELL","pg_isready -U joplin"]
   interval: 10s
   timeout: 5s
   retries: 5

joplin-server:
 image: joplin/server:latest
 restart: always
 ports:
  -"22300:22300"
 depends_on:
 joplin-db:
  condition: service_healthy
 environment:
  APP_BASE_URL: http://127.0.0.1/8:22300
  DB_CLIENT: pg
  POSTGRES_HOST: joplin-db
  POSTGRES_PORT: 5432
  POSTGRES_DATABASE: joplin
  POSTGRES_PASSWORD: Btctgrp6.eve
